export const dynamic = "force-dynamic";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Unna as UnnaFont } from "next/font/google";
import localFont from "next/font/local";
import WidgetSection from "@/components/common/WidgetSection";
import { Toaster } from "react-hot-toast";
import { BookingFormContextProvider } from "@/context/BookingFormContext";
import { fetchDropdownDataAPI, fetchFromAPI } from "@/lib/api";

export const metadata = {
  title: "Skyline Hospitals",
  description: "Generated by create next app",
};

export const graphik = localFont({
  src: [
    {
      path: "../../public/fonts/Graphik-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Black.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/Graphik-Super.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-graphik",
  preload: true,
  display: "swap",
});

const unna = UnnaFont({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-unna",
});

export default async function RootLayout({ children }) {
  const { data } = await fetchFromAPI("site-settings");
  const { site_settings, social_links } = data;

  return (
    <html lang="en">
      <body className={` ${graphik.variable}  ${unna.variable}`}>
        <BookingFormContextProvider>
          <Header site_settings={site_settings} social_links={social_links} />
          <main className="flex-grow">{children}</main>
          <WidgetSection />
          <Footer site_settings={site_settings} social_links={social_links} />
          <Toaster position="top-right" />
        </BookingFormContextProvider>
      </body>
    </html>
  );
}
