import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Unna as UnnaFont } from "next/font/google";
import localFont from "next/font/local";

export const metadata = {
  title: "Skyline Hospitals",
  description: "Generated by create next app",
};

// export const fordAntenna = localFont({
//   src: [
//     {
//       path: "../../public/fonts/StretchProRegular.woff2",
//       weight: "400", // use "400" or "normal" instead of "100"
//       style: "normal",
//     },
//   ],
//   variable: "--font-fordAntenna",
//   preload: true,
//   display: "swap",
// });

const unna = UnnaFont({
  subsets: ["latin"],
  weight: ["400", "700"], // Unna doesn’t support 100–900, only normal/bold
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${unna.className} ${fordAntenna.variable}`}> */}
      <body className={`${unna.className} `}>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
