export const dynamic = "force-dynamic";

import "./globals.css";
// import { GoogleTagManager } from "@next/third-parties/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Unna as UnnaFont } from "next/font/google";
import localFont from "next/font/local";
import WidgetSection from "@/components/common/WidgetSection";
import { Toaster } from "react-hot-toast";
import { BookingFormContextProvider } from "@/context/BookingFormContext";
import { fetchDropdownDataAPI, fetchFromAPI } from "@/lib/api";
import Script from "next/script";
import RecaptchaProvider from "@/components/RecaptchaProvider";

export const metadata = {
  title: "Skyline Hospitals",
  description: "Generated by create next app",
};

export const graphik = localFont({
  src: [
    { path: "../../public/fonts/Graphik-Thin.woff2", weight: "100", style: "normal" },
    { path: "../../public/fonts/Graphik-Extralight.woff2", weight: "200", style: "normal" },
    { path: "../../public/fonts/Graphik-Light.woff2", weight: "300", style: "normal" },
    { path: "../../public/fonts/Graphik-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/Graphik-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/fonts/Graphik-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../../public/fonts/Graphik-Bold.woff2", weight: "700", style: "normal" },
    { path: "../../public/fonts/Graphik-Black.woff2", weight: "800", style: "normal" },
    { path: "../../public/fonts/Graphik-Super.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-graphik",
  preload: true,
  display: "swap",
});

const unna = UnnaFont({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-unna",
});

export default async function RootLayout({ children }) {
  let data = { site_settings: null, social_links: [], policies: [] };
  let services = [];

  try {
    const siteSettingsResponse = await fetchFromAPI("site-settings");
    data = siteSettingsResponse.data || data;
  } catch (error) {
    console.error("Failed to fetch site settings:", error.message);
  }

  try {
    const servicesResponse = await fetchDropdownDataAPI("get-services");
    services = servicesResponse.data || [];
  } catch (error) {
    console.error("Failed to fetch services:", error.message);
  }

  const { site_settings, social_links, policies } = data;

  return (
    <html lang="en">
      {/* <GoogleTagManager gtmId="GTM-XYZ" /> */}
      <body className={`${graphik.variable} ${unna.variable}`}>
        <RecaptchaProvider>
          <BookingFormContextProvider>
            <Header site_settings={site_settings} social_links={social_links} services={services} />
            <main className="flex-grow">{children}</main>
            <WidgetSection site_settings={site_settings} />
            <Footer site_settings={site_settings} social_links={social_links} policies={policies} services={services} />
            <Toaster position="top-right" />
          </BookingFormContextProvider>
        </RecaptchaProvider>

        {/* ✅ Add the Tawk.to Script here */}
        <Script id="tawkto-script" strategy="afterInteractive">
          {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),
              s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/690aee654ff5db195c83385f/1j99b6g18';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
